# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration
---
require: rubocop-rake

AllCops:
  # Opt-in to new cops by default
  NewCops: enable
  Exclude:
    - "bin/bundle"
    - "db/schema.rb"
    - "vendor/**/*"

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: always_ignore

Layout/LineLength:
  Exclude:
    - "db/migrate/*.rb"

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Exclude:
    - "db/migrate/*.rb"

Metrics/BlockLength:
  AllowedMethods:
    - namespace

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*.rb"

Rake/Desc:
  Exclude:
    - rakelib/database.rake

Style/Documentation:
  Exclude:
    - "db/migrate/*.rb"

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
