---
version: "3.9"
services:
  web:
    build:
      context: .
      target: development
    command: ["/usr/bin/env", "RAILS_LOG_TO_STDOUT=true", "/app/bin/rails", "server", "--binding", "0.0.0.0"]
    depends_on:
      - db
    tty: true
    stop_grace_period: "3s"
    environment:
      - APP_HOST=localhost
      - APP_PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432
      - TZ=Australia/Melbourne
      - DOMAIN_API_KEY=key_219ebd48b03175453be6690187de3a85
      - SCRAPFLY_API_KEY=scp-live-69d0c9e32fe74f7cac00b5db33f4c99f
    ports:
      - "127.0.0.1:3000:3000/tcp"
    tmpfs:
      - /app/tmp:mode=755,uid=1000,gid=1000
  worker:
    build:
      context: .
      target: development
    command: ["/usr/bin/env", "RAILS_LOG_TO_STDOUT=true", "/app/bin/bundle", "exec", "good_job", "start"]
    depends_on:
      - db
    tty: true
    stop_grace_period: "3s"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432
      - TZ=Australia/Melbourne
      - DOMAIN_API_KEY=key_219ebd48b03175453be6690187de3a85
      - SCRAPFLY_API_KEY=scp-live-69d0c9e32fe74f7cac00b5db33f4c99f
    tmpfs:
      - /app/tmp:mode=755,uid=1000,gid=1000
  db:
    image: postgres:16-alpine
    stop_grace_period: "3s"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "postgres:/var/lib/postgresql/data"

volumes:
  postgres: {}
