---
version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      target: development
    command: ["/bin/bash"]
    depends_on:
      - db
    stop_grace_period: "3s"
    tty: true
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/treehouse
      - TZ=Australia/Melbourne
  db:
    image: postgres:16-alpine
    stop_grace_period: "3s"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "postgres:/var/lib/postgresql/data"

volumes:
  postgres: {}
