---
version: "3.9"
services:
  web:
    build:
      context: .
      target: development
    command: ["/app/bin/rails", "server", "--binding", "0.0.0.0"]
    depends_on:
      - db
    tty: true
    stop_grace_period: "3s"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/treehouse
      - TZ=Australia/Melbourne
    ports:
      - "127.0.0.1:3000:3000/tcp"
    tmpfs:
      - /app/tmp:mode=755,uid=1000,gid=1000
  worker:
    build:
      context: .
      target: development
    command: ["/app/bin/bundle", "exec", "good_job", "start"]
    depends_on:
      - db
    tty: true
    stop_grace_period: "3s"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/treehouse
      - TZ=Australia/Melbourne
    tmpfs:
      - /app/tmp:mode=755,uid=1000,gid=1000
  db:
    image: postgres:16-alpine
    stop_grace_period: "3s"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "postgres:/var/lib/postgresql/data"

volumes:
  postgres: {}
